---
name: Deploy Fusion Bundle to Sandbox with Custom Action

on:
  push:
    # Adjust this list of branches if you want to use this action
    # for PRs and pushes.
    branches:
      - sandbox
  # This action lets you run this Action manually.
  workflow_dispatch:

jobs:
  new-deployer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        if: ${{ success() }}
        uses: actions/checkout@v3

      # This configures NodeJS for our purposes.
      - name: Set up Node
        if: ${{ success() }}
        uses: actions/setup-node@v3
        with:
          #### IF YOU NEED TO CHANGE YOUR NODE VERSION, JUST CHANGE THIS NUMBER
          node-version: 20
          cache: npm

      # Installs NodeJS dependencies.
      - name: Install dependencies
        if: ${{ success() }}
        run: |
          npm install

      # Build the code.
      - name: Build the Fusion Bundle
        if: ${{ success() }}
        run: |
          echo "./node_modules/.bin" >> $GITHUB_PATH
          fusion build
          fusion zip

      - name: Perform the deploy
        if: ${{ success() }}
        uses: arcxp/deploy-action@v1
        with:
          org-id: arctesting2
          api-key: "${{ secrets.SANDBOX_DEPLOYER_TOKEN }}"
          api-hostname: api.sandbox.arctesting2.arcpublishing.com
          pagebuilder-version: 4.1.2
          bundle-prefix: action-demo-1

