---
name: Deploy Fusion Bundle to Sandbox
on:
  push:
    branches:
      - sandbox
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Config settings
        run: |
          echo "environment=SANDBOX" >> $GITHUB_ENV
          echo "endpoint=api.sandbox.arctesting2.arcpublishing.com" >> $GITHUB_ENV
          echo "timestamp=$(date +%s)" >> $GITHUB_ENV
          echo "token=${{ secrets.SANDBOX_DEPLOYER_TOKEN }}" >> $GITHUB_ENV

      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: |
          npm install --prefix . @slack/client axios@0.27 form-data

      - name: Build the Fusion Bundle
        run: |
          npm run build
          npm run zip

      - name: Upload the Fusion Bundle
        run: |
          curl -vvv \
            -H 'Accept: application/json' \
            -H "Authorization: Bearer ${{ env.token }}" \
            -F "bundleName=${{ env.timestamp }}-${GITHUB_HEAD_REF}-${GITHUB_SHA}" \
            -F "bundle=@dist/fusion-bundle.zip" \
            "https://${{env.endpoint}}/deployments/fusion/bundles"
          echo "EXIT: $?"

      - name: Deploy the Fusion Bundle
        run: |
          curl -vvv \
            -H 'Accept: application/json' \
            -H "Authorization: Bearer ${{ env.token }}" \
            -X POST \
            "https://${{env.endpoint}}/deployments/fusion/services?bundle=${{ env.timestamp }}-${GITHUB_HEAD_REF}-${GITHUB_SHA}&version=latest"
          echo "EXIT: $?"
