---
name: Deploy Fusion Bundle to Sandbox
on:
  push:
    branches:
      - sandbox
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: |
          npm install --prefix . @slack/client axios@0.27 form-data

      - name: Build the Fusion Bundle
        run: |
          npm run build
          npm run zip
